export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';

export const ADD_FOOD = 'ADD_FOOD';
export const GET_FOOD = 'GET_FOOD';

export const GET_USER = 'GET_USER';
export const REMOVE_USER = 'REMOVE_USER';

export const GET_GOAL = 'GET_GOAL';
export const UPDATE_GOAL = 'UPDATE_GOAL';

export const ADD_FOOD_TO_DIARY = 'ADD_FOOD_TO_DIARY';
export const SELECT_MEAL_TYPE = 'SELECT_MEAL_TYPE';
export const SELECT_DIARY_DATE = 'SELECT_DIARY_DATE';
export const REVISED_ADD_FOOD_TO_DIARY = 'REVISED_ADD_FOOD_TO_DIARY';
export const ADD_TO_BREAKFAST = 'ADD_TO_BREAKFAST';
export const ADD_TO_LUNCH = 'ADD_TO_LUNCH';
export const ADD_TO_DINNER = 'ADD_TO_DINNER';
export const ADD_TO_SNACK = 'ADD_TO_SNACK';
export const RECEIVE_DATABASE_QUERY = 'RECEIVE_DATABASE_QUERY';
export const RETRIEVING_FOOD_FROM_DATABASE = 'RETRIEVING_FOOD_FROM_DATABASE';
